### ISSUE TITLE
12 slots and not enough and not all spawns are set?

### ISSUE THREAD

**Issue by Driesboy** [svilex/SkyWars-PocketMine#3]
## Issue description

i have set slots to 12
i have set 12 spawn point
and if i will create a sign he say not all spawns are set
## Errors - CrashDumps

```
---
name: Skywars
slot: 12
world: Skywars
countdown: 30
maxGameTime: 600
void_Y: -1
spawns:
  1:
    x: -857.000000
    "y": 45.000000
    z: -118.000000
    yaw: 205
    pitch: 7
  2:
    x: -824.000000
    "y": 44.000000
    z: -113.000000
    yaw: 196
    pitch: 14
  3:
    x: -792.000000
    "y": 44.000000
    z: -120.000000
    yaw: 188
    pitch: 1
  4:
    x: -766.000000
    "y": 43.000000
    z: -147.000000
    yaw: 88
    pitch: 1
  5:
    x: -759.000000
    "y": 43.000000
    z: -180.000000
    yaw: 87
    pitch: 3
  6:
    x: -768.000000
    "y": 43.000000
    z: -211.000000
    yaw: 116
    pitch: 13
  7:
    x: -794.000000
    "y": 43.000000
    z: -236.000000
    yaw: 39
    pitch: 4
  8:
    x: -824.000000
    "y": 43.000000
    z: -243.000000
    yaw: 5
    pitch: 15
  9:
    x: -854.000000
    "y": 43.000000
    z: -234.000000
    yaw: 356
    pitch: 9
  10:
    x: -880.000000
    "y": 44.000000
    z: -207.000000
    yaw: 302
    pitch: 6
  11:
    x: -886.000000
    "y": 43.000000
    z: -177.000000
    yaw: 280
    pitch: 7
  12:
    x: -880.000000
    "y": 44.000000
    z: -145.000000
    yaw: 279
    pitch: 14
...
```

## Versions

- **SW_VERSION**:  v0.2

- **POCKETMINE**:  ImagicalMine

- **PHP**: 7
